"""Room 17 (2F Hallway) -- `Hall2F Floor Planks`, round V3 wave A.

    python floor3.py                 # texture + GLB + place + repaint the slab
    python floor3.py --nopatch       # geometry only

WHAT THE CRITICS SAID, AND WHERE EACH FIX LIVES
-----------------------------------------------
Two of the nine round-1 critics had the floor as their subject and both named
it as the thing that gave the render away in the first two seconds; three more
named it while judging something else.  Their five complaints:

  1 "no plank structure ... you cannot tell where one board ends and the next
     begins"                                   -> the TILE (planktex.py)
  2 "no plank-to-plank variation"              -> the TILE + this piece
  3 "no butt joints, it is sheet goods"        -> the TILE
  4 "no sheen ... the same value at 2 ft as at 25 ft"   -> this piece
  5 "value is inverted / two stops too dark"   -> measured, see VALUE below

1-3 cannot be done in a GLB.  The photographs' clean floor meters mean|d1|
3.2-7.4 at their own 450x600, which is grain at roughly a 0.1 in scale; the
near field runs about 0.013 ft per pixel, so matching it with vertex colour
needs sample spacing near 0.02 ft, which over this room's 113 sq ft is a
quarter of a million vertices -- 30x the whole-room budget.  `roomkit.glb` has
no image-texture API, but the ROOM SLAB does: `rooms.floor_texture`, keyed into
`frontend/js/textures.js`, which ROOM-BRIEF names as the floor-surface lever.
So the fine scale comes from a NEW tile, `plank_grey`, generated by
`planktex.py` -- 12 boards of 8 in over an 8 ft repeat at 96 px/ft, with
micro-bevelled long edges, staggered butt joints two per board per repeat,
per-segment value (sd 3.6%), three periodic grain octaves, mineral streaks and
knots.  A new key, not an edit to `wood`: six other rooms use `wood`, and
`wood` is unusable here anyway (256 px over 2.2 ft, every column CONSTANT down
its length, no joints, and a flat 15%-dark 2 px seam every board -- which is
the "butt-lines read as UV seams" complaint from round 2).

This GLB is then a thin satin WEAR LAYER over that tile, carrying the four
things a repeating tile cannot:

  * SHEEN.  The slab material is hard-coded `roughness 0.9` in house.js, so the
    slab alone can never be satin.  This layer is roughness 0.24 at 34%
    opacity, so the composite is a matte textured floor seen through a glossy
    film -- which is what a satin-finish LVP physically is.  Per-board crown
    (0.0016 ft over 0.667) plus a slow lengthwise undulation break the specular
    into bands running DOWN the boards instead of lying on the floor as one
    sheet.
  * LIGHT FALLOFF.  Baked pools under the five ceiling cans that see this floor
    (positions taken from ceiling2.py's CANS, which were solved by
    un-projecting the saturated blobs through these poses), and fall-off into
    the alcove and the far corners.  In `hallway_looking_towards_stairs` the
    photo's floor runs 127 in the near field and 203 under the can at the
    master-bedroom door -- a factor of 1.6 -- and our floor was one value end
    to end.
  * CONTACT.  A wall-line AO ramp: 0.50 ft to 0.88, with a 0.055 ft hairline at
    0.80 hard against the wall, on every polygon edge except the open stairwell
    cut (light comes UP through that one).  That is the "no occlusion in any
    reentrant corner, no hairline where two materials meet" theme, on the one
    surface that meets every wall in the room.
  * BREAKING THE REPEAT.  The tile repeats every 8 ft.  This layer adds a
    per-board value step (hard, at x = k*8/12, which registers EXACTLY with the
    tile because slab UVs are u = local_x / size) and a slow non-repeating
    lengthwise drift, so the 12-board pattern never reads twice the same.

NO runner contact shadow is baked here: `Hall2F Floor Runner` already carries
its own decal (its GLB spans the full 3.86 ft strip width against a 2.5 ft rug
body).  Two overlapping shadows is the "nested rings" failure.  Wave B owns it.

VALUE -- measured, not taken from the critic
--------------------------------------------
floor_b said "light greige washed oak within about 15% of the wall grey".  The
photographs do not say that.  Clean floor patches against clean wall patches
in the same frame (fmeter3.py):

    photo                             wall   floor  ratio
    hallway_with_white_runner_rug    167.5   119.1  0.711
    hallway_looking_towards_stairs   155.0   127.2  0.821
    two_closed_white_doors_2         168.0   127.1  0.756
    two_closed_white_doors_1         172.2   134.2  0.779

so 0.71-0.82, mean 0.767 -- not 0.85, and the hue is a COOL near-neutral grey
(rgb 128.7/126.4/128.6, 121.5/117.9/124.7), not greige.  The round-1 floor
really was about half the photo's luminance; the build that shipped before this
one had already corrected that, and this one holds the same ratio.  What was
still missing was everything above.
"""

import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "circ"))
sys.path.insert(0, r"C:\Users\Manuel\Desktop\Pro\3d HA\tools")

from ckit import *                                            # noqa: F401,F403,E402
from ckit import _req                                         # noqa: E402
from roomkit.glb import Part                                  # noqa: E402
from roomkit.place import place                               # noqa: E402

ROOM = 17
TEXTURE = "plank_grey"          # frontend/js/textures.js, size 8 ft
TEX_FEET = 8.0
PLANKS_PER_TILE = 12
PITCH = TEX_FEET / PLANKS_PER_TILE        # 0.6667 ft = 8 in boards

# The 10-vertex L, room-local feet (anchor world 6.70, 18.00, 6.55).
POLY = [(11.92, 6.81), (7.61, 6.81), (7.61, 16.89), (3.86, 16.89),
        (3.86, 16.15), (0.0, 16.15), (0.0, 10.77), (3.86, 10.77),
        (3.86, 0.0), (11.92, 0.0)]

# Three axis-aligned bands whose union is exactly that L.  Split on x only, so
# a board is never cut along its length by a region boundary.
REGIONS = [
    (0.00, 3.86, 10.77, 16.15),     # west alcove   (three-door dead end)
    (3.86, 7.61, 0.00, 16.89),      # walking strip + west half of north block
    (7.61, 11.92, 0.00, 6.81),      # east half of the north block
]
OPEN_EDGE = ((11.92, 6.81), (7.61, 6.81))    # the stairwell cut -- no AO here

# Ceiling cans, room-local (x, z, strength) -- from ceiling2.py CANS.  The one
# at (10.03, 12.74) is over the open stair shaft and lights no floor here.
CANS = [(5.80, 7.18, 1.00), (7.75, 7.18, 0.86), (6.10, 4.18, 0.86),
        (8.22, 4.10, 0.86), (1.93, 13.46, 0.58)]
CAN_R = 3.30                    # pool radius on the floor, ft
CAN_A = float(os.environ.get("H17_CAN", 0.185))

# Doorways, as (x0, z0, x1, z1) of the threshold line in room-local feet,
# derived from the openings table (edge i runs vertex i -> vertex i+1 and the
# offset is measured along that direction), plus the inward normal.  A closed
# white leaf and its casing are the brightest thing near the floor in every one
# of these photographs and they wash a pool onto the boards in front of them --
# `hallway_with_white_runner_rug` meters 219 on the floor at the bath threshold
# against 119 in the middle of the hall.
DOORS = [
    ((4.67, 16.89), (7.46, 16.89), (0.0, -1.0)),    # 133 bathroom
    ((0.576, 16.15), (3.113, 16.15), (0.0, -1.0)),  # 127 Rios room
    ((0.0, 12.163), (0.0, 15.062), (1.0, 0.0)),     # 125 room 25
    ((0.362, 10.77), (3.116, 10.77), (0.0, 1.0)),   # 136 guest room
    ((7.828, 0.0), (10.691, 0.0), (0.0, 1.0)),      # 137 master bed
]
DOOR_A = float(os.environ.get("H17_DOOR", 0.20))
DOOR_R = 1.85                   # how far the wash reaches into the room, ft

Y0 = 0.0168                     # over the slab (0.010), under the runner (0.020)
CROWN = 0.0016                  # per-board crown -> a specular band down each
WAVE = 0.0011                   # slow lengthwise undulation

XN = 4                          # samples across one board (+1 at each edge)
ROW = 0.34                      # row pitch down a board, ft

# COLOR_0 is exported as `_srgb_to_linear(c)` in a normalized ubyte, so any
# channel authored above 1.0 pegs at 255 and the whole upward half of the field
# is thrown away (round 3's floor metered mean|d1| 0.08 -- algebraically flat --
# for exactly this reason).  Centre on NOM and divide the albedo back out.  The
# baked light field here has to swing 0.72..1.45, so NOM is 0.68: linear 0.415,
# one ubyte step 0.95% relative, which is under the banding threshold for a
# gradient this soft.
NOM = 0.68

# OPACITY IS A TRADE, and it is worth stating.  This layer is the only thing in
# the room that can carry either sheen or a light gradient (house.js hard-codes
# the slab at roughness 0.9 and one flat floor_color), but every point of
# opacity it takes is a point of the tile's grain it hides -- measured, the tile
# loses roughly (1 - opacity) of its contrast into the render.  0.44 is where
# the render's fine gradient still lands near the photograph's while the vertex
# field still has enough authority to move the composite ~14% end to end.
WEAR = Material("h17wear4", os.environ.get("H17_WEAR", "#8e8d8e"),
                roughness=float(os.environ.get("H17_ROUGH", 0.20)),
                metallic=0.0,
                opacity=float(os.environ.get("H17_OP", 0.44)),
                double_sided=False)
NOSE = Material("h17nose4", "#4e4b4d", roughness=0.55, metallic=0.0)

FLOOR_COLOR = os.environ.get("H17_FLOOR", "#626161")


# ------------------------------------------------------------------ helpers
def h(*a):
    """Deterministic hash -> [0,1), keyed on the GLOBAL board index so a board
    clipped by a region boundary gets the same tone on both sides."""
    v = 0x9E3779B9
    for x in a:
        v = (v ^ (int(x) * 0x85EBCA6B + 0xC2B2AE35)) & 0xFFFFFFFF
        v = ((v << 13) | (v >> 19)) & 0xFFFFFFFF
        v = (v * 0x27D4EB2F + 0x165667B1) & 0xFFFFFFFF
    return ((v >> 8) & 0xFFFFFF) / 16777216.0


def sym(*a):
    return h(*a) * 2.0 - 1.0


def _seg_dist(px, pz, a, b):
    ax, az = a
    bx, bz = b
    dx, dz = bx - ax, bz - az
    L2 = dx * dx + dz * dz
    t = 0.0 if L2 == 0 else max(0.0, min(1.0, ((px - ax) * dx + (pz - az) * dz) / L2))
    return math.hypot(px - (ax + t * dx), pz - (az + t * dz))


EDGES = [(POLY[i], POLY[(i + 1) % len(POLY)]) for i in range(len(POLY))]
AO_EDGES = [e for e in EDGES if e != OPEN_EDGE]


def wall_dist(px, pz):
    return min(_seg_dist(px, pz, a, b) for (a, b) in AO_EDGES)


AO_RAMP = 0.50          # how far the wall's occlusion reaches onto the floor
AO_DEEP = 0.88          # value at the wall line
AO_LINE = 0.055         # the hairline hard against the skirting
AO_LINE_V = 0.795


def ao_at(x, z):
    d = wall_dist(x, z)
    a = AO_DEEP + (1.0 - AO_DEEP) * min(1.0, d / AO_RAMP) ** 0.85
    if d < AO_LINE:
        a = min(a, AO_LINE_V + (AO_DEEP - AO_LINE_V) * (d / AO_LINE))
    # the open stairwell cut is lit from below: lift, do not darken
    dopen = _seg_dist(x, z, *OPEN_EDGE)
    if dopen < 1.1:
        a *= 1.0 + 0.035 * (1.0 - dopen / 1.1)
    return a


BASE_LIGHT = 0.845      # the mid-hall walking strip, which has no can over it


def _door_wash(x, z):
    """The white leaf + casing of a closed door is the brightest thing near
    this floor, and it throws a pool onto the boards in front of it.  Measured
    in `hallway_with_white_runner_rug`: 219 on the floor at the bath threshold
    against 119 in the middle of the hall.  Falls off over DOOR_R, and dies
    laterally over 0.7 ft past each jamb so a doorway does not light the corner
    beside it."""
    s = 0.0
    for (a, b, n) in DOORS:
        # distance into the room, and position along the threshold
        din = (x - a[0]) * n[0] + (z - a[1]) * n[1]
        if din < -0.05 or din > 3.0 * DOOR_R:
            continue
        tx, tz = b[0] - a[0], b[1] - a[1]
        ln = math.hypot(tx, tz)
        t = ((x - a[0]) * tx + (z - a[1]) * tz) / (ln * ln)
        over = max(0.0, -t, t - 1.0) * ln            # ft past the jamb
        s += (DOOR_A * math.exp(-(max(0.0, din) / DOOR_R) ** 2)
              * math.exp(-(over / 0.70) ** 2))
    return s


def light(x, z):
    """The baked light field: cans, door washes, and the white skirting's own
    bounce standing off every wall.  Soft-capped so the vertex colour cannot
    clip -- see NOM."""
    s = BASE_LIGHT
    for (cx, cz, k) in CANS:
        r2 = ((x - cx) ** 2 + (z - cz) ** 2) / (CAN_R * CAN_R)
        s += CAN_A * k * math.exp(-r2)
    s += _door_wash(x, z)
    # the white skirting bounces into the boards a few inches off the wall --
    # OUTSIDE the contact hairline, which is what makes the two read as
    # separate events rather than one grey smudge
    s += 0.085 * math.exp(-((wall_dist(x, z) - 0.42) / 0.38) ** 2)
    if s > 1.24:                       # soft knee, never a hard clip
        s = 1.24 + 0.45 * (s - 1.24)
    return s


# --------------------------------------------------------------- the sheet
def piece_floor():
    m = Model()
    nv = 0

    for (rx0, rx1, rz0, rz1) in REGIONS:
        k0 = int(math.floor(rx0 / PITCH + 1e-6))
        k1 = int(math.ceil(rx1 / PITCH - 1e-6))
        for gk in range(k0, k1):
            bx0 = max(rx0, gk * PITCH)
            bx1 = min(rx1, (gk + 1) * PITCH)
            if bx1 - bx0 < 0.010:
                continue

            # THE BOARD'S OWN VALUE.  Hard-stepped at the board edge because
            # every board here is its own vertex strip -- an interpolated grid
            # turns per-board value into a soft swell, which is what round 3's
            # floor did and what the critics read as "monotone board to board".
            # This registers with the tile's own boards: slab UVs are
            # u = local_x / size, so tile board j starts at local_x = j*PITCH.
            board = 1.0 + 0.040 * sym(gk, 3)
            # slow lengthwise drift, different per board, non-repeating -- this
            # is what stops the tile's 8 ft repeat reading as a repeat
            dl = 4.2 + 5.5 * h(gk, 4)
            dp = h(gk, 5) * 6.2832
            d2 = 9.0 + 7.0 * h(gk, 14)
            d2p = h(gk, 15) * 6.2832
            ph1 = h(gk, 6) * 6.2832

            xs = [bx0 + (bx1 - bx0) * i / XN for i in range(XN + 1)]
            nx = len(xs)
            nrow = max(2, int(round((rz1 - rz0) / ROW)))
            rows = [rz0 + (rz1 - rz0) * j / nrow for j in range(nrow + 1)]

            verts, cols, tris = [], [], []
            for z in rows:
                drift = (0.024 * math.sin(z / dl + dp)
                         + 0.015 * math.sin(z / d2 + d2p))
                for x in xs:
                    t = (x - gk * PITCH) / PITCH        # 0..1 across the board
                    s = NOM * board * (1.0 + drift) * ao_at(x, z) * light(x, z)
                    s = min(0.999, s)
                    y = (Y0 + CROWN * math.sin(math.pi * min(1.0, max(0.0, t)))
                         + WAVE * (0.5 + 0.5 * math.sin(z / 1.55 + ph1)))
                    verts.append((x, y, z))
                    # the photographs' floor meters R+0.9 G-1.6 B+0.7 about its
                    # own mean -- a cool near-neutral, not blue-violet
                    cols.append((min(1.0, s * 1.004), min(1.0, s * 0.993),
                                 min(1.0, s * 1.006)))

            for j in range(len(rows) - 1):
                for i in range(nx - 1):
                    a = j * nx + i
                    tris += [(a, a + nx, a + 1), (a + 1, a + nx, a + nx + 1)]
            m.add(Part(verts, tris, smooth=True, colors=cols), WEAR)
            nv += len(verts)

    # Nosing on the open stairwell cut (polygon edge 0).  Without it the slab
    # ends in a raw sawn line right where `p_runner` and `p_down` look at it.
    bx(m, NOSE, 7.61, 11.92, -0.085, 0.0188, 6.745, 6.812)
    print(f"  verts {nv}")
    return m


# ------------------------------------------------------------------- drive
def save_and_place(name, m, room=ROOM, fname=None):
    path = os.path.join(HERE, "glb",
                        (fname or name.replace(" ", "_").lower()) + ".glb")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    m.save(path)
    lo, hi = m.bounds()
    pos = ((lo[0] + hi[0]) / 2.0, lo[1], (lo[2] + hi[2]) / 2.0)
    res = place(name, path, room, pos=pos, rot_y_deg=0.0, scale=1.0)
    kb = os.path.getsize(path) / 1024.0
    print(f"  {name:24s} size={tuple(round(hi[i]-lo[i],2) for i in range(3))}"
          f"  {kb:7.1f} KB  {res['action']}")
    return kb


if __name__ == "__main__":
    if "--notex" not in sys.argv:
        import planktex
        import numpy as np
        from PIL import Image
        a = planktex.build()
        Image.fromarray(a, mode="L").save(planktex.OUT, optimize=True)
        print(f"  tile {os.path.getsize(planktex.OUT)/1024:.0f} KB "
              f"mean {a.mean():.1f} sd {a.std():.2f}")
    save_and_place("Hall2F Floor Planks", piece_floor())
    if "--nopatch" not in sys.argv:
        _req("PATCH", f"/api/house/room/{ROOM}",
             {"floor_color": FLOOR_COLOR, "floor_texture": TEXTURE})
        print(f"  room {ROOM} floor_color -> {FLOOR_COLOR}, "
              f"floor_texture -> {TEXTURE}")
