// Built-in wall/floor texture presets (frontend/textures/*.png, generated by
// scripts/gen_textures.py). Textures are near-white so material.color tints
// them; `size` is how many world feet one texture repeat covers.
import * as THREE from 'three';

export const TEXTURE_PRESETS = {
  plaster:  { name: 'Plaster',     url: 'textures/plaster.png',  size: 8, use: 'wall' },
  brick:    { name: 'Brick',       url: 'textures/brick.png',    size: 4, use: 'wall' },
  concrete: { name: 'Concrete',    url: 'textures/concrete.png', size: 6, use: 'wall' },
  wood:     { name: 'Wood planks', url: 'textures/wood.png',     size: 4, use: 'floor' },
  tile:     { name: 'Tile',        url: 'textures/tile.png',     size: 4, use: 'floor' },
  carpet:   { name: 'Carpet',      url: 'textures/carpet.png',   size: 6, use: 'floor' },
};

const loader = new THREE.TextureLoader();

// Module-level caches: buildHouse creates fresh materials on every rebuild,
// so textures must outlive rebuilds (same pattern as models.js) and are
// never disposed. Clones are per repeat-count because `repeat` lives on the
// Texture, not the material.
const baseCache = new Map();   // key -> THREE.Texture
const tiledCache = new Map();  // "key:rx:ry" -> THREE.Texture

function baseTexture(key) {
  let tex = baseCache.get(key);
  if (!tex) {
    tex = loader.load(TEXTURE_PRESETS[key].url, () => {
      // clones share this texture's Source; ones made before the image
      // arrived need a version bump now that there's data to upload
      for (const [k, t] of tiledCache) {
        if (k.startsWith(`${key}:`)) t.needsUpdate = true;
      }
    });
    tex.colorSpace = THREE.SRGBColorSpace;
    tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
    baseCache.set(key, tex);
  }
  return tex;
}

// Returns a texture repeating (rx, ry) times, or null for no/unknown key
// (an unknown key stored in the DB degrades to the plain color).
export function getTiledTexture(key, rx, ry) {
  if (!key || !TEXTURE_PRESETS[key]) return null;
  const cacheKey = `${key}:${rx.toFixed(3)}:${ry.toFixed(3)}`;
  let tex = tiledCache.get(cacheKey);
  if (!tex) {
    const base = baseTexture(key);
    tex = base.clone(); // clone() flags needsUpdate itself
    tex.repeat.set(rx, ry);
    // an image-less texture flagged for upload makes the renderer warn every
    // frame; unflag until the loader callback above re-flags it with data
    if (!base.image) tex.version = 0;
    tiledCache.set(cacheKey, tex);
  }
  return tex;
}

export function textureSize(key) {
  return TEXTURE_PRESETS[key]?.size || 4;
}

// Fills a <select> with "none" + all presets, wall-leaning ones first.
export function fillTextureSelect(selectEl) {
  const opt = (value, label) => {
    const o = document.createElement('option');
    o.value = value;
    o.textContent = label;
    selectEl.appendChild(o);
  };
  selectEl.innerHTML = '';
  opt('', '— none —');
  const entries = Object.entries(TEXTURE_PRESETS)
    .sort((a, b) => (a[1].use === 'wall' ? 0 : 1) - (b[1].use === 'wall' ? 0 : 1));
  for (const [key, p] of entries) opt(key, p.name);
}
